import { lazy } from 'react';
export const AdminRoutes = [
  { path: '/dashboard', element: lazy(() => import('../pages/dashboard/DashboardPage')) },
  { path: '/users', element: lazy(() => import('../pages/users/UsersPage')) },
  { path: '/games', element: lazy(() => import('../pages/games/GamesPage')) },
  { path: '/rounds', element: lazy(() => import('../pages/rounds/RoundsPage')) },
  { path: '/rounds/create', element: lazy(() => import('../pages/rounds/CreateRoundPage')) },
  { path: '/results', element: lazy(() => import('../pages/results/ResultsPage')) },
  { path: '/results/declare/:roundId', element: lazy(() => import('../pages/results/DeclareResultPage')) },
  { path: '/wagers', element: lazy(() => import('../pages/wagers/WagersPage')) },
  { path: '/wagers/:id', element: lazy(() => import('../pages/wagers/WagerDetailPageWrapper')) },
  { path: '/payments', element: lazy(() => import('../pages/payments/PaymentsPage')) },
  { path: '/payments/:id', element: lazy(() => import('../pages/payments/PaymentDetailPageWrapper')) },
  { path: '/banners', element: lazy(() => import('../pages/banners/BannersPage')) },
  { path: '/bonuses', element: lazy(() => import('../pages/bonuses/BonusesPage')) },
  { path: '/notifications', element: lazy(() => import('../pages/notifications/NotificationsPage')) },
  { path: '/support', element: lazy(() => import('../pages/support/TicketsPage')) },
  { path: '/settings', element: lazy(() => import('../pages/settings/SettingsPage')) },
  { path: '/audit-logs', element: lazy(() => import('../pages/audit-logs/AuditLogsPage')) },
];